-- Category audit: relabel listings whose own website does not support the
-- category they were filed under, and add every category the site does show.
-- Generated by scripts/apply-category-audit.cjs, applied to production with
-- sg_categories.py. No category link is ever removed; running this twice is
-- harmless because every statement is either idempotent or sets the same value.

SET NAMES utf8mb4;

-- 49 listings move to the category their website is mostly about.

UPDATE listings SET category_id = 5 WHERE id = 23; -- non-mascots
UPDATE listings SET category_id = 3 WHERE id = 24; -- princesses
UPDATE listings SET category_id = 8 WHERE id = 39; -- holidays
UPDATE listings SET category_id = 8 WHERE id = 42; -- holidays
UPDATE listings SET category_id = 3 WHERE id = 49; -- princesses
UPDATE listings SET category_id = 8 WHERE id = 57; -- holidays
UPDATE listings SET category_id = 3 WHERE id = 64; -- princesses
UPDATE listings SET category_id = 5 WHERE id = 65; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 67; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 89; -- non-mascots
UPDATE listings SET category_id = 2 WHERE id = 94; -- mascots
UPDATE listings SET category_id = 3 WHERE id = 97; -- princesses
UPDATE listings SET category_id = 8 WHERE id = 102; -- holidays
UPDATE listings SET category_id = 5 WHERE id = 103; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 106; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 107; -- non-mascots
UPDATE listings SET category_id = 1 WHERE id = 109; -- superheroes
UPDATE listings SET category_id = 1 WHERE id = 115; -- superheroes
UPDATE listings SET category_id = 3 WHERE id = 117; -- princesses
UPDATE listings SET category_id = 8 WHERE id = 128; -- holidays
UPDATE listings SET category_id = 3 WHERE id = 134; -- princesses
UPDATE listings SET category_id = 8 WHERE id = 145; -- holidays
UPDATE listings SET category_id = 10 WHERE id = 163; -- magicians
UPDATE listings SET category_id = 5 WHERE id = 237; -- non-mascots
UPDATE listings SET category_id = 3 WHERE id = 242; -- princesses
UPDATE listings SET category_id = 5 WHERE id = 244; -- non-mascots
UPDATE listings SET category_id = 8 WHERE id = 248; -- holidays
UPDATE listings SET category_id = 1 WHERE id = 263; -- superheroes
UPDATE listings SET category_id = 6 WHERE id = 281; -- clowns
UPDATE listings SET category_id = 5 WHERE id = 312; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 316; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 333; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 335; -- non-mascots
UPDATE listings SET category_id = 10 WHERE id = 336; -- magicians
UPDATE listings SET category_id = 5 WHERE id = 337; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 338; -- non-mascots
UPDATE listings SET category_id = 3 WHERE id = 348; -- princesses
UPDATE listings SET category_id = 3 WHERE id = 350; -- princesses
UPDATE listings SET category_id = 1 WHERE id = 353; -- superheroes
UPDATE listings SET category_id = 9 WHERE id = 355; -- fairy
UPDATE listings SET category_id = 1 WHERE id = 361; -- superheroes
UPDATE listings SET category_id = 1 WHERE id = 367; -- superheroes
UPDATE listings SET category_id = 5 WHERE id = 370; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 380; -- non-mascots
UPDATE listings SET category_id = 5 WHERE id = 381; -- non-mascots
UPDATE listings SET category_id = 1 WHERE id = 383; -- superheroes
UPDATE listings SET category_id = 5 WHERE id = 405; -- non-mascots
UPDATE listings SET category_id = 3 WHERE id = 406; -- princesses
UPDATE listings SET category_id = 5 WHERE id = 471; -- non-mascots

-- 239 categories the sites clearly offer are added.

INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (6, 6); -- clowns
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (6, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (6, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (8, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (10, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (11, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (12, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (16, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (16, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (17, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (17, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (19, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (21, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (23, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (24, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (24, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (25, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (26, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (26, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (27, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (27, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (27, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (29, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (30, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (40, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (42, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (42, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (43, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (47, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (48, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (49, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (50, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (53, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (56, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (56, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (56, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (57, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (59, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (60, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (61, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (62, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (63, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (64, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (65, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (65, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (71, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (71, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (72, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (73, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (74, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (74, 7); -- pirates
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (74, 4); -- star-wars
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (77, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (78, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (83, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (90, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (92, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (98, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (103, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (106, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (106, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (106, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (109, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (110, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (110, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (110, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (115, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (116, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (116, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (116, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (118, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (119, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (123, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (123, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (123, 4); -- star-wars
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (123, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (128, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (130, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (131, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (132, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (133, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (134, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (134, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (143, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (145, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (162, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (163, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (167, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (168, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (168, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (168, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (171, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (171, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (172, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (172, 4); -- star-wars
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (172, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (174, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (175, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (175, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (176, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (177, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (178, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (183, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (187, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (189, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (194, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (194, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (194, 7); -- pirates
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (194, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (197, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (202, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (205, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (205, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (208, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (208, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (213, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (218, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (220, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (220, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (221, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (225, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (226, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (227, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (231, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (234, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (237, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (239, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (239, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (239, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (242, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (242, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (242, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (242, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (243, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (243, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (243, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (243, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (243, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (244, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (244, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (248, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (255, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (255, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (255, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (260, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (263, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (263, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (263, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (285, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (285, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (289, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (292, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (294, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (294, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (294, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (294, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (294, 4); -- star-wars
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (294, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (295, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (296, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (296, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (298, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (304, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (306, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (306, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (307, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (307, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (308, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (312, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (316, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (324, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (324, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (333, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (335, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (335, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (336, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (336, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (336, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (337, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (338, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (338, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (343, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (345, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (348, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (348, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (349, 6); -- clowns
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (349, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (350, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (353, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (353, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (353, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (353, 4); -- star-wars
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (353, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (355, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (356, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (356, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (356, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (361, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (367, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (367, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (367, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (370, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (370, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (370, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (373, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (373, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (373, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (380, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (381, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (382, 10); -- magicians
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (382, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (382, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (383, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (383, 2); -- mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (383, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (383, 1); -- superheroes
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (384, 9); -- fairy
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (384, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (384, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (384, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (405, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (406, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (406, 3); -- princesses
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (419, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (426, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (428, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (431, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (440, 6); -- clowns
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (440, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (465, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (466, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (471, 8); -- holidays
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (471, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (472, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (473, 4); -- star-wars
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (474, 4); -- star-wars
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (479, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (481, 5); -- non-mascots
INSERT IGNORE INTO listing_categories (listing_id, category_id) VALUES (482, 5); -- non-mascots
