/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ClownsRouteImport } from './routes/clowns'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FairiesRouteImport } from './routes/fairies'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListYourBusinessRouteImport } from './routes/list-your-business'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MagiciansRouteImport } from './routes/magicians'
import { Route as MascotsRouteImport } from './routes/mascots'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NonMascotCharactersRouteImport } from './routes/non-mascot-characters'
import { Route as PartyBuilderRouteImport } from './routes/party-builder'
import { Route as PiratesRouteImport } from './routes/pirates'
import { Route as PrincessesRouteImport } from './routes/princesses'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StarWarsRouteImport } from './routes/star-wars'
import { Route as SuperheroesRouteImport } from './routes/superheroes'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as MagiciansIndexRouteImport } from './routes/magicians.index'
import { Route as MagiciansDallasTxRouteImport } from './routes/magicians.dallas-tx'
import { Route as PrincessesIndexRouteImport } from './routes/princesses.index'
import { Route as PrincessesDallasTxRouteImport } from './routes/princesses.dallas-tx'
import { Route as SuperheroesIndexRouteImport } from './routes/superheroes.index'
import { Route as SuperheroesDallasTxRouteImport } from './routes/superheroes.dallas-tx'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor.analytics'
import { Route as VendorCalendarRouteImport } from './routes/vendor.calendar'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorLeadsRouteImport } from './routes/vendor.leads'
import { Route as VendorMessagesRouteImport } from './routes/vendor.messages'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorQuotesRouteImport } from './routes/vendor.quotes'
import { Route as VendorsSlugRouteImport } from './routes/vendors.$slug'
import { Route as CategorySlugLocationRouteImport } from './routes/category.$slug.$location'
import { Route as MagiciansDallasTxIndexRouteImport } from './routes/magicians.dallas-tx.index'
import { Route as MagiciansDallasTxKidsPartiesRouteImport } from './routes/magicians.dallas-tx.kids-parties'
import { Route as PrincessesDallasTxIndexRouteImport } from './routes/princesses.dallas-tx.index'
import { Route as PrincessesDallasTxBirthdayPartiesRouteImport } from './routes/princesses.dallas-tx.birthday-parties'
import { Route as SuperheroesDallasTxIndexRouteImport } from './routes/superheroes.dallas-tx.index'
import { Route as SuperheroesDallasTxBirthdayPartiesRouteImport } from './routes/superheroes.dallas-tx.birthday-parties'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClownsRoute = ClownsRouteImport.update({
  id: '/clowns',
  path: '/clowns',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FairiesRoute = FairiesRouteImport.update({
  id: '/fairies',
  path: '/fairies',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourBusinessRoute = ListYourBusinessRouteImport.update({
  id: '/list-your-business',
  path: '/list-your-business',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MagiciansRoute = MagiciansRouteImport.update({
  id: '/magicians',
  path: '/magicians',
  getParentRoute: () => rootRouteImport,
} as any)
const MascotsRoute = MascotsRouteImport.update({
  id: '/mascots',
  path: '/mascots',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NonMascotCharactersRoute = NonMascotCharactersRouteImport.update({
  id: '/non-mascot-characters',
  path: '/non-mascot-characters',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyBuilderRoute = PartyBuilderRouteImport.update({
  id: '/party-builder',
  path: '/party-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PiratesRoute = PiratesRouteImport.update({
  id: '/pirates',
  path: '/pirates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincessesRoute = PrincessesRouteImport.update({
  id: '/princesses',
  path: '/princesses',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StarWarsRoute = StarWarsRouteImport.update({
  id: '/star-wars',
  path: '/star-wars',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperheroesRoute = SuperheroesRouteImport.update({
  id: '/superheroes',
  path: '/superheroes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MagiciansIndexRoute = MagiciansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MagiciansRoute,
} as any)
const MagiciansDallasTxRoute = MagiciansDallasTxRouteImport.update({
  id: '/dallas-tx',
  path: '/dallas-tx',
  getParentRoute: () => MagiciansRoute,
} as any)
const PrincessesIndexRoute = PrincessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrincessesRoute,
} as any)
const PrincessesDallasTxRoute = PrincessesDallasTxRouteImport.update({
  id: '/dallas-tx',
  path: '/dallas-tx',
  getParentRoute: () => PrincessesRoute,
} as any)
const SuperheroesIndexRoute = SuperheroesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperheroesRoute,
} as any)
const SuperheroesDallasTxRoute = SuperheroesDallasTxRouteImport.update({
  id: '/dallas-tx',
  path: '/dallas-tx',
  getParentRoute: () => SuperheroesRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/vendor/analytics',
  path: '/vendor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorCalendarRoute = VendorCalendarRouteImport.update({
  id: '/vendor/calendar',
  path: '/vendor/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLeadsRoute = VendorLeadsRouteImport.update({
  id: '/vendor/leads',
  path: '/vendor/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorMessagesRoute = VendorMessagesRouteImport.update({
  id: '/vendor/messages',
  path: '/vendor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/vendor/profile',
  path: '/vendor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorQuotesRoute = VendorQuotesRouteImport.update({
  id: '/vendor/quotes',
  path: '/vendor/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsSlugRoute = VendorsSlugRouteImport.update({
  id: '/vendors/$slug',
  path: '/vendors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugLocationRoute = CategorySlugLocationRouteImport.update({
  id: '/$location',
  path: '/$location',
  getParentRoute: () => CategorySlugRoute,
} as any)
const MagiciansDallasTxIndexRoute = MagiciansDallasTxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MagiciansDallasTxRoute,
} as any)
const MagiciansDallasTxKidsPartiesRoute =
  MagiciansDallasTxKidsPartiesRouteImport.update({
    id: '/kids-parties',
    path: '/kids-parties',
    getParentRoute: () => MagiciansDallasTxRoute,
  } as any)
const PrincessesDallasTxIndexRoute = PrincessesDallasTxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrincessesDallasTxRoute,
} as any)
const PrincessesDallasTxBirthdayPartiesRoute =
  PrincessesDallasTxBirthdayPartiesRouteImport.update({
    id: '/birthday-parties',
    path: '/birthday-parties',
    getParentRoute: () => PrincessesDallasTxRoute,
  } as any)
const SuperheroesDallasTxIndexRoute =
  SuperheroesDallasTxIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SuperheroesDallasTxRoute,
  } as any)
const SuperheroesDallasTxBirthdayPartiesRoute =
  SuperheroesDallasTxBirthdayPartiesRouteImport.update({
    id: '/birthday-parties',
    path: '/birthday-parties',
    getParentRoute: () => SuperheroesDallasTxRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/clowns': typeof ClownsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/fairies': typeof FairiesRoute
  '/favorites': typeof FavoritesRoute
  '/holidays': typeof HolidaysRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/magicians': typeof MagiciansRouteWithChildren
  '/mascots': typeof MascotsRoute
  '/messages': typeof MessagesRoute
  '/non-mascot-characters': typeof NonMascotCharactersRoute
  '/party-builder': typeof PartyBuilderRoute
  '/pirates': typeof PiratesRoute
  '/princesses': typeof PrincessesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quotes': typeof QuotesRoute
  '/request-quote': typeof RequestQuoteRoute
  '/search': typeof SearchRoute
  '/star-wars': typeof StarWarsRoute
  '/superheroes': typeof SuperheroesRouteWithChildren
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/magicians/dallas-tx': typeof MagiciansDallasTxRouteWithChildren
  '/princesses/dallas-tx': typeof PrincessesDallasTxRouteWithChildren
  '/superheroes/dallas-tx': typeof SuperheroesDallasTxRouteWithChildren
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/calendar': typeof VendorCalendarRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/quotes': typeof VendorQuotesRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/magicians/': typeof MagiciansIndexRoute
  '/princesses/': typeof PrincessesIndexRoute
  '/superheroes/': typeof SuperheroesIndexRoute
  '/category/$slug/$location': typeof CategorySlugLocationRoute
  '/magicians/dallas-tx/kids-parties': typeof MagiciansDallasTxKidsPartiesRoute
  '/princesses/dallas-tx/birthday-parties': typeof PrincessesDallasTxBirthdayPartiesRoute
  '/superheroes/dallas-tx/birthday-parties': typeof SuperheroesDallasTxBirthdayPartiesRoute
  '/magicians/dallas-tx/': typeof MagiciansDallasTxIndexRoute
  '/princesses/dallas-tx/': typeof PrincessesDallasTxIndexRoute
  '/superheroes/dallas-tx/': typeof SuperheroesDallasTxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/clowns': typeof ClownsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/fairies': typeof FairiesRoute
  '/favorites': typeof FavoritesRoute
  '/holidays': typeof HolidaysRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/mascots': typeof MascotsRoute
  '/messages': typeof MessagesRoute
  '/non-mascot-characters': typeof NonMascotCharactersRoute
  '/party-builder': typeof PartyBuilderRoute
  '/pirates': typeof PiratesRoute
  '/privacy': typeof PrivacyRoute
  '/quotes': typeof QuotesRoute
  '/request-quote': typeof RequestQuoteRoute
  '/search': typeof SearchRoute
  '/star-wars': typeof StarWarsRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/calendar': typeof VendorCalendarRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/quotes': typeof VendorQuotesRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/magicians': typeof MagiciansIndexRoute
  '/princesses': typeof PrincessesIndexRoute
  '/superheroes': typeof SuperheroesIndexRoute
  '/category/$slug/$location': typeof CategorySlugLocationRoute
  '/magicians/dallas-tx/kids-parties': typeof MagiciansDallasTxKidsPartiesRoute
  '/princesses/dallas-tx/birthday-parties': typeof PrincessesDallasTxBirthdayPartiesRoute
  '/superheroes/dallas-tx/birthday-parties': typeof SuperheroesDallasTxBirthdayPartiesRoute
  '/magicians/dallas-tx': typeof MagiciansDallasTxIndexRoute
  '/princesses/dallas-tx': typeof PrincessesDallasTxIndexRoute
  '/superheroes/dallas-tx': typeof SuperheroesDallasTxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/clowns': typeof ClownsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/fairies': typeof FairiesRoute
  '/favorites': typeof FavoritesRoute
  '/holidays': typeof HolidaysRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-your-business': typeof ListYourBusinessRoute
  '/login': typeof LoginRoute
  '/magicians': typeof MagiciansRouteWithChildren
  '/mascots': typeof MascotsRoute
  '/messages': typeof MessagesRoute
  '/non-mascot-characters': typeof NonMascotCharactersRoute
  '/party-builder': typeof PartyBuilderRoute
  '/pirates': typeof PiratesRoute
  '/princesses': typeof PrincessesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quotes': typeof QuotesRoute
  '/request-quote': typeof RequestQuoteRoute
  '/search': typeof SearchRoute
  '/star-wars': typeof StarWarsRoute
  '/superheroes': typeof SuperheroesRouteWithChildren
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/magicians/dallas-tx': typeof MagiciansDallasTxRouteWithChildren
  '/princesses/dallas-tx': typeof PrincessesDallasTxRouteWithChildren
  '/superheroes/dallas-tx': typeof SuperheroesDallasTxRouteWithChildren
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/calendar': typeof VendorCalendarRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/leads': typeof VendorLeadsRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/quotes': typeof VendorQuotesRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/magicians/': typeof MagiciansIndexRoute
  '/princesses/': typeof PrincessesIndexRoute
  '/superheroes/': typeof SuperheroesIndexRoute
  '/category/$slug/$location': typeof CategorySlugLocationRoute
  '/magicians/dallas-tx/kids-parties': typeof MagiciansDallasTxKidsPartiesRoute
  '/princesses/dallas-tx/birthday-parties': typeof PrincessesDallasTxBirthdayPartiesRoute
  '/superheroes/dallas-tx/birthday-parties': typeof SuperheroesDallasTxBirthdayPartiesRoute
  '/magicians/dallas-tx/': typeof MagiciansDallasTxIndexRoute
  '/princesses/dallas-tx/': typeof PrincessesDallasTxIndexRoute
  '/superheroes/dallas-tx/': typeof SuperheroesDallasTxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/clowns'
    | '/compare'
    | '/contact'
    | '/explore'
    | '/fairies'
    | '/favorites'
    | '/holidays'
    | '/how-it-works'
    | '/list-your-business'
    | '/login'
    | '/magicians'
    | '/mascots'
    | '/messages'
    | '/non-mascot-characters'
    | '/party-builder'
    | '/pirates'
    | '/princesses'
    | '/privacy'
    | '/quotes'
    | '/request-quote'
    | '/search'
    | '/star-wars'
    | '/superheroes'
    | '/terms'
    | '/category/$slug'
    | '/magicians/dallas-tx'
    | '/princesses/dallas-tx'
    | '/superheroes/dallas-tx'
    | '/vendor/analytics'
    | '/vendor/calendar'
    | '/vendor/dashboard'
    | '/vendor/leads'
    | '/vendor/messages'
    | '/vendor/profile'
    | '/vendor/quotes'
    | '/vendors/$slug'
    | '/magicians/'
    | '/princesses/'
    | '/superheroes/'
    | '/category/$slug/$location'
    | '/magicians/dallas-tx/kids-parties'
    | '/princesses/dallas-tx/birthday-parties'
    | '/superheroes/dallas-tx/birthday-parties'
    | '/magicians/dallas-tx/'
    | '/princesses/dallas-tx/'
    | '/superheroes/dallas-tx/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/clowns'
    | '/compare'
    | '/contact'
    | '/explore'
    | '/fairies'
    | '/favorites'
    | '/holidays'
    | '/how-it-works'
    | '/list-your-business'
    | '/login'
    | '/mascots'
    | '/messages'
    | '/non-mascot-characters'
    | '/party-builder'
    | '/pirates'
    | '/privacy'
    | '/quotes'
    | '/request-quote'
    | '/search'
    | '/star-wars'
    | '/terms'
    | '/category/$slug'
    | '/vendor/analytics'
    | '/vendor/calendar'
    | '/vendor/dashboard'
    | '/vendor/leads'
    | '/vendor/messages'
    | '/vendor/profile'
    | '/vendor/quotes'
    | '/vendors/$slug'
    | '/magicians'
    | '/princesses'
    | '/superheroes'
    | '/category/$slug/$location'
    | '/magicians/dallas-tx/kids-parties'
    | '/princesses/dallas-tx/birthday-parties'
    | '/superheroes/dallas-tx/birthday-parties'
    | '/magicians/dallas-tx'
    | '/princesses/dallas-tx'
    | '/superheroes/dallas-tx'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/clowns'
    | '/compare'
    | '/contact'
    | '/explore'
    | '/fairies'
    | '/favorites'
    | '/holidays'
    | '/how-it-works'
    | '/list-your-business'
    | '/login'
    | '/magicians'
    | '/mascots'
    | '/messages'
    | '/non-mascot-characters'
    | '/party-builder'
    | '/pirates'
    | '/princesses'
    | '/privacy'
    | '/quotes'
    | '/request-quote'
    | '/search'
    | '/star-wars'
    | '/superheroes'
    | '/terms'
    | '/category/$slug'
    | '/magicians/dallas-tx'
    | '/princesses/dallas-tx'
    | '/superheroes/dallas-tx'
    | '/vendor/analytics'
    | '/vendor/calendar'
    | '/vendor/dashboard'
    | '/vendor/leads'
    | '/vendor/messages'
    | '/vendor/profile'
    | '/vendor/quotes'
    | '/vendors/$slug'
    | '/magicians/'
    | '/princesses/'
    | '/superheroes/'
    | '/category/$slug/$location'
    | '/magicians/dallas-tx/kids-parties'
    | '/princesses/dallas-tx/birthday-parties'
    | '/superheroes/dallas-tx/birthday-parties'
    | '/magicians/dallas-tx/'
    | '/princesses/dallas-tx/'
    | '/superheroes/dallas-tx/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  ClownsRoute: typeof ClownsRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  FairiesRoute: typeof FairiesRoute
  FavoritesRoute: typeof FavoritesRoute
  HolidaysRoute: typeof HolidaysRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListYourBusinessRoute: typeof ListYourBusinessRoute
  LoginRoute: typeof LoginRoute
  MagiciansRoute: typeof MagiciansRouteWithChildren
  MascotsRoute: typeof MascotsRoute
  MessagesRoute: typeof MessagesRoute
  NonMascotCharactersRoute: typeof NonMascotCharactersRoute
  PartyBuilderRoute: typeof PartyBuilderRoute
  PiratesRoute: typeof PiratesRoute
  PrincessesRoute: typeof PrincessesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  QuotesRoute: typeof QuotesRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  SearchRoute: typeof SearchRoute
  StarWarsRoute: typeof StarWarsRoute
  SuperheroesRoute: typeof SuperheroesRouteWithChildren
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRouteWithChildren
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorCalendarRoute: typeof VendorCalendarRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorLeadsRoute: typeof VendorLeadsRoute
  VendorMessagesRoute: typeof VendorMessagesRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorQuotesRoute: typeof VendorQuotesRoute
  VendorsSlugRoute: typeof VendorsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clowns': {
      id: '/clowns'
      path: '/clowns'
      fullPath: '/clowns'
      preLoaderRoute: typeof ClownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairies': {
      id: '/fairies'
      path: '/fairies'
      fullPath: '/fairies'
      preLoaderRoute: typeof FairiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-business': {
      id: '/list-your-business'
      path: '/list-your-business'
      fullPath: '/list-your-business'
      preLoaderRoute: typeof ListYourBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magicians': {
      id: '/magicians'
      path: '/magicians'
      fullPath: '/magicians'
      preLoaderRoute: typeof MagiciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mascots': {
      id: '/mascots'
      path: '/mascots'
      fullPath: '/mascots'
      preLoaderRoute: typeof MascotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-mascot-characters': {
      id: '/non-mascot-characters'
      path: '/non-mascot-characters'
      fullPath: '/non-mascot-characters'
      preLoaderRoute: typeof NonMascotCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-builder': {
      id: '/party-builder'
      path: '/party-builder'
      fullPath: '/party-builder'
      preLoaderRoute: typeof PartyBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pirates': {
      id: '/pirates'
      path: '/pirates'
      fullPath: '/pirates'
      preLoaderRoute: typeof PiratesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/princesses': {
      id: '/princesses'
      path: '/princesses'
      fullPath: '/princesses'
      preLoaderRoute: typeof PrincessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/star-wars': {
      id: '/star-wars'
      path: '/star-wars'
      fullPath: '/star-wars'
      preLoaderRoute: typeof StarWarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superheroes': {
      id: '/superheroes'
      path: '/superheroes'
      fullPath: '/superheroes'
      preLoaderRoute: typeof SuperheroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magicians/': {
      id: '/magicians/'
      path: '/'
      fullPath: '/magicians/'
      preLoaderRoute: typeof MagiciansIndexRouteImport
      parentRoute: typeof MagiciansRoute
    }
    '/magicians/dallas-tx': {
      id: '/magicians/dallas-tx'
      path: '/dallas-tx'
      fullPath: '/magicians/dallas-tx'
      preLoaderRoute: typeof MagiciansDallasTxRouteImport
      parentRoute: typeof MagiciansRoute
    }
    '/princesses/': {
      id: '/princesses/'
      path: '/'
      fullPath: '/princesses/'
      preLoaderRoute: typeof PrincessesIndexRouteImport
      parentRoute: typeof PrincessesRoute
    }
    '/princesses/dallas-tx': {
      id: '/princesses/dallas-tx'
      path: '/dallas-tx'
      fullPath: '/princesses/dallas-tx'
      preLoaderRoute: typeof PrincessesDallasTxRouteImport
      parentRoute: typeof PrincessesRoute
    }
    '/superheroes/': {
      id: '/superheroes/'
      path: '/'
      fullPath: '/superheroes/'
      preLoaderRoute: typeof SuperheroesIndexRouteImport
      parentRoute: typeof SuperheroesRoute
    }
    '/superheroes/dallas-tx': {
      id: '/superheroes/dallas-tx'
      path: '/dallas-tx'
      fullPath: '/superheroes/dallas-tx'
      preLoaderRoute: typeof SuperheroesDallasTxRouteImport
      parentRoute: typeof SuperheroesRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/vendor/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/calendar': {
      id: '/vendor/calendar'
      path: '/vendor/calendar'
      fullPath: '/vendor/calendar'
      preLoaderRoute: typeof VendorCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/leads': {
      id: '/vendor/leads'
      path: '/vendor/leads'
      fullPath: '/vendor/leads'
      preLoaderRoute: typeof VendorLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/messages': {
      id: '/vendor/messages'
      path: '/vendor/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof VendorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/quotes': {
      id: '/vendor/quotes'
      path: '/vendor/quotes'
      fullPath: '/vendor/quotes'
      preLoaderRoute: typeof VendorQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$slug': {
      id: '/vendors/$slug'
      path: '/vendors/$slug'
      fullPath: '/vendors/$slug'
      preLoaderRoute: typeof VendorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$location': {
      id: '/category/$slug/$location'
      path: '/$location'
      fullPath: '/category/$slug/$location'
      preLoaderRoute: typeof CategorySlugLocationRouteImport
      parentRoute: typeof CategorySlugRoute
    }
    '/magicians/dallas-tx/': {
      id: '/magicians/dallas-tx/'
      path: '/'
      fullPath: '/magicians/dallas-tx/'
      preLoaderRoute: typeof MagiciansDallasTxIndexRouteImport
      parentRoute: typeof MagiciansDallasTxRoute
    }
    '/magicians/dallas-tx/kids-parties': {
      id: '/magicians/dallas-tx/kids-parties'
      path: '/kids-parties'
      fullPath: '/magicians/dallas-tx/kids-parties'
      preLoaderRoute: typeof MagiciansDallasTxKidsPartiesRouteImport
      parentRoute: typeof MagiciansDallasTxRoute
    }
    '/princesses/dallas-tx/': {
      id: '/princesses/dallas-tx/'
      path: '/'
      fullPath: '/princesses/dallas-tx/'
      preLoaderRoute: typeof PrincessesDallasTxIndexRouteImport
      parentRoute: typeof PrincessesDallasTxRoute
    }
    '/princesses/dallas-tx/birthday-parties': {
      id: '/princesses/dallas-tx/birthday-parties'
      path: '/birthday-parties'
      fullPath: '/princesses/dallas-tx/birthday-parties'
      preLoaderRoute: typeof PrincessesDallasTxBirthdayPartiesRouteImport
      parentRoute: typeof PrincessesDallasTxRoute
    }
    '/superheroes/dallas-tx/': {
      id: '/superheroes/dallas-tx/'
      path: '/'
      fullPath: '/superheroes/dallas-tx/'
      preLoaderRoute: typeof SuperheroesDallasTxIndexRouteImport
      parentRoute: typeof SuperheroesDallasTxRoute
    }
    '/superheroes/dallas-tx/birthday-parties': {
      id: '/superheroes/dallas-tx/birthday-parties'
      path: '/birthday-parties'
      fullPath: '/superheroes/dallas-tx/birthday-parties'
      preLoaderRoute: typeof SuperheroesDallasTxBirthdayPartiesRouteImport
      parentRoute: typeof SuperheroesDallasTxRoute
    }
  }
}

interface MagiciansDallasTxRouteChildren {
  MagiciansDallasTxKidsPartiesRoute: typeof MagiciansDallasTxKidsPartiesRoute
  MagiciansDallasTxIndexRoute: typeof MagiciansDallasTxIndexRoute
}

const MagiciansDallasTxRouteChildren: MagiciansDallasTxRouteChildren = {
  MagiciansDallasTxKidsPartiesRoute: MagiciansDallasTxKidsPartiesRoute,
  MagiciansDallasTxIndexRoute: MagiciansDallasTxIndexRoute,
}

const MagiciansDallasTxRouteWithChildren =
  MagiciansDallasTxRoute._addFileChildren(MagiciansDallasTxRouteChildren)

interface MagiciansRouteChildren {
  MagiciansDallasTxRoute: typeof MagiciansDallasTxRouteWithChildren
  MagiciansIndexRoute: typeof MagiciansIndexRoute
}

const MagiciansRouteChildren: MagiciansRouteChildren = {
  MagiciansDallasTxRoute: MagiciansDallasTxRouteWithChildren,
  MagiciansIndexRoute: MagiciansIndexRoute,
}

const MagiciansRouteWithChildren = MagiciansRoute._addFileChildren(
  MagiciansRouteChildren,
)

interface PrincessesDallasTxRouteChildren {
  PrincessesDallasTxBirthdayPartiesRoute: typeof PrincessesDallasTxBirthdayPartiesRoute
  PrincessesDallasTxIndexRoute: typeof PrincessesDallasTxIndexRoute
}

const PrincessesDallasTxRouteChildren: PrincessesDallasTxRouteChildren = {
  PrincessesDallasTxBirthdayPartiesRoute:
    PrincessesDallasTxBirthdayPartiesRoute,
  PrincessesDallasTxIndexRoute: PrincessesDallasTxIndexRoute,
}

const PrincessesDallasTxRouteWithChildren =
  PrincessesDallasTxRoute._addFileChildren(PrincessesDallasTxRouteChildren)

interface PrincessesRouteChildren {
  PrincessesDallasTxRoute: typeof PrincessesDallasTxRouteWithChildren
  PrincessesIndexRoute: typeof PrincessesIndexRoute
}

const PrincessesRouteChildren: PrincessesRouteChildren = {
  PrincessesDallasTxRoute: PrincessesDallasTxRouteWithChildren,
  PrincessesIndexRoute: PrincessesIndexRoute,
}

const PrincessesRouteWithChildren = PrincessesRoute._addFileChildren(
  PrincessesRouteChildren,
)

interface SuperheroesDallasTxRouteChildren {
  SuperheroesDallasTxBirthdayPartiesRoute: typeof SuperheroesDallasTxBirthdayPartiesRoute
  SuperheroesDallasTxIndexRoute: typeof SuperheroesDallasTxIndexRoute
}

const SuperheroesDallasTxRouteChildren: SuperheroesDallasTxRouteChildren = {
  SuperheroesDallasTxBirthdayPartiesRoute:
    SuperheroesDallasTxBirthdayPartiesRoute,
  SuperheroesDallasTxIndexRoute: SuperheroesDallasTxIndexRoute,
}

const SuperheroesDallasTxRouteWithChildren =
  SuperheroesDallasTxRoute._addFileChildren(SuperheroesDallasTxRouteChildren)

interface SuperheroesRouteChildren {
  SuperheroesDallasTxRoute: typeof SuperheroesDallasTxRouteWithChildren
  SuperheroesIndexRoute: typeof SuperheroesIndexRoute
}

const SuperheroesRouteChildren: SuperheroesRouteChildren = {
  SuperheroesDallasTxRoute: SuperheroesDallasTxRouteWithChildren,
  SuperheroesIndexRoute: SuperheroesIndexRoute,
}

const SuperheroesRouteWithChildren = SuperheroesRoute._addFileChildren(
  SuperheroesRouteChildren,
)

interface CategorySlugRouteChildren {
  CategorySlugLocationRoute: typeof CategorySlugLocationRoute
}

const CategorySlugRouteChildren: CategorySlugRouteChildren = {
  CategorySlugLocationRoute: CategorySlugLocationRoute,
}

const CategorySlugRouteWithChildren = CategorySlugRoute._addFileChildren(
  CategorySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  ClownsRoute: ClownsRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  FairiesRoute: FairiesRoute,
  FavoritesRoute: FavoritesRoute,
  HolidaysRoute: HolidaysRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListYourBusinessRoute: ListYourBusinessRoute,
  LoginRoute: LoginRoute,
  MagiciansRoute: MagiciansRouteWithChildren,
  MascotsRoute: MascotsRoute,
  MessagesRoute: MessagesRoute,
  NonMascotCharactersRoute: NonMascotCharactersRoute,
  PartyBuilderRoute: PartyBuilderRoute,
  PiratesRoute: PiratesRoute,
  PrincessesRoute: PrincessesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  QuotesRoute: QuotesRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  SearchRoute: SearchRoute,
  StarWarsRoute: StarWarsRoute,
  SuperheroesRoute: SuperheroesRouteWithChildren,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRouteWithChildren,
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorCalendarRoute: VendorCalendarRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorLeadsRoute: VendorLeadsRoute,
  VendorMessagesRoute: VendorMessagesRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorQuotesRoute: VendorQuotesRoute,
  VendorsSlugRoute: VendorsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
